const navToggle=document.querySelector('.nav-toggle');const siteNav=document.querySelector('.site-nav');
navToggle?.addEventListener('click',()=>{const open=siteNav.classList.toggle('open');navToggle.setAttribute('aria-expanded',String(open))});
siteNav?.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{siteNav.classList.remove('open');navToggle?.setAttribute('aria-expanded','false')}));

document.querySelectorAll('.filter').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('.filter').forEach(b=>b.classList.remove('active'));button.classList.add('active');const selected=button.dataset.filter;document.querySelectorAll('.project-card').forEach(card=>card.classList.toggle('hidden',selected!=='all'&&!card.dataset.category.includes(selected)))}));

const projectDetails={
  capsa:{title:'CAPSA Paradise Land',category:'UX/UI · SEO · Menu digital · Automatisation',visual:'linear-gradient(135deg,#103b32,#176a50 55%,#d09b28)',description:"Conception de l'écosystème digital d'un parc de loisirs et espace événementiel à Gafsa.",problem:"L'offre du lieu était dispersée et manquait d'une présentation digitale claire permettant aux visiteurs de découvrir les espaces, les événements, le restaurant et les possibilités de réservation.",solution:"Définition de l'architecture, création des maquettes UI, conception d'un menu digital interactif, optimisation SEO locale, contenus marketing et scénarios d'automatisation pour les publications événementielles.",impact:"Une expérience plus cohérente, une meilleure visibilité locale et un parcours plus simple entre découverte, consultation et prise de contact.",tools:['Figma','WordPress','SEO local','UX/UI','Make','Menu digital'],gallery:[]},
  'rx-contracts':{title:'RX Contracts',category:'Python · Django · Gestion documentaire',visual:'linear-gradient(135deg,#2367ff,#20c7d9)',description:'Plateforme interne de gestion des contrats, prestataires, sites, litiges, documents et échéances.',problem:"Les informations étaient dispersées, les échéances difficiles à suivre et les oublis pouvaient créer des risques administratifs.",solution:"Création d'un tableau de bord centralisé avec rôles, recherche, pagination, alertes automatiques, documents et suivi métier.",impact:"Centralisation de l'information, meilleur suivi des échéances et réduction des oublis.",tools:['Python','Django','SQL','Alertes','Dashboard'],gallery:['images/rx-contracts-1.png','images/rx-contracts-2.png','images/rx-contracts-3.png']},
  'assistant-ia':{title:'Assistant IA de triage',category:'Make · OpenAI · Airtable',visual:'linear-gradient(135deg,#7c3aed,#db2777)',description:'Workflow IA pour analyser, classer et structurer automatiquement des demandes entrantes.',problem:"Le tri manuel des emails et formulaires demande du temps, crée des retards et rend le suivi irrégulier.",solution:"Un scénario Make extrait les informations, qualifie la priorité, crée une fiche de suivi et génère une réponse brouillon avec validation humaine.",impact:"Traitement plus rapide, demandes mieux structurées et diminution des oublis.",tools:['Make','OpenAI','Airtable','Notion','Google Sheets'],gallery:['images/assistant-ia-automation-1.png','images/assistant-ia-automation-2.png']},
  'agent-seo':{title:'Agent IA SEO WordPress',category:'IA · SEO · WordPress',visual:'linear-gradient(135deg,#111827,#334155)',description:'Prototype d’agent IA qui analyse une page WordPress et propose des optimisations SEO actionnables.',problem:"Les audits manuels sont répétitifs et certaines pages sont publiées sans structure SEO complète.",solution:"Analyse des titres, métadonnées, structure Hn, contenu, maillage interne et opportunités d'amélioration, puis génération d'un plan d'action.",impact:"Audits plus rapides, recommandations standardisées et meilleure organisation éditoriale.",tools:['WordPress','OpenAI','Make','SEO','Search Console'],gallery:['images/agent-ia-seo.png']},
  'rib-generator':{title:'RIB Generator',category:'Python · Automatisation locale',visual:'linear-gradient(135deg,#059669,#14b8a6)',description:'Application desktop pour générer automatiquement des fichiers comptables TXT conformes.',problem:"La saisie manuelle était lente et exposée aux erreurs de format.",solution:"Interface guidée, validations, nommage automatique, sauvegarde et génération du fichier final.",impact:"Gain de temps, meilleure fiabilité et utilisation simple pour des utilisateurs non techniques.",tools:['Python','CustomTkinter','TXT','Validation'],gallery:['images/rib-generator.png']},
  airbnb:{title:'Application de réservation No-Code',category:'Bubble · Figma · UML · Base de données',visual:'linear-gradient(135deg,#ff625f,#ff9b93)',description:'Projet de conception d’une application de réservation inspirée d’Airbnb.',problem:"Concevoir en trois semaines une application réaliste, cohérente et démontrable avec plusieurs profils utilisateurs.",solution:"Définition des cas d'utilisation, modèle de données, parcours voyageur/hôte, maquettes, règles métier et MVP Bubble.",impact:"Démonstration d'une démarche produit complète, de l'analyse à la construction du prototype.",tools:['Bubble','Figma','UML','Merise','User Stories'],gallery:[]}
};

const modal=document.querySelector('#project-modal');
function openModal(id){const p=projectDetails[id];if(!p||!modal)return;document.querySelector('#modal-title').textContent=p.title;document.querySelector('#modal-category').textContent=p.category;document.querySelector('#modal-description').textContent=p.description;document.querySelector('#modal-problem').textContent=p.problem;document.querySelector('#modal-solution').textContent=p.solution;document.querySelector('#modal-impact').textContent=p.impact;document.querySelector('#modal-visual').style.background=p.visual;document.querySelector('#modal-tools').innerHTML=p.tools.map(x=>`<span>${x}</span>`).join('');document.querySelector('#modal-gallery').innerHTML=p.gallery.map((src,i)=>`<figure class="modal-shot"><img src="${src}" alt="${p.title} - capture ${i+1}"><figcaption>${p.title} · capture ${i+1}</figcaption></figure>`).join('');modal.classList.add('open');modal.setAttribute('aria-hidden','false');document.body.classList.add('modal-lock')}
function closeModal(){modal?.classList.remove('open');modal?.setAttribute('aria-hidden','true');document.body.classList.remove('modal-lock')}
document.querySelectorAll('.project-more').forEach(b=>b.addEventListener('click',()=>openModal(b.dataset.project)));document.querySelectorAll('[data-close-modal]').forEach(x=>x.addEventListener('click',closeModal));document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()});

const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');observer.unobserve(entry.target)}}),{threshold:.12});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));
document.querySelector('#year').textContent=new Date().getFullYear();
