function upgradePortfolio(){
 document.title='Sana Rachdi | Développement · IA · No-Code';
 const m=(s,v)=>{const e=document.querySelector(s);if(e)e.content=v};
 m('meta[name="description"]',"Portfolio de Sana Rachdi, conceptrice d'applications orientée développement, IA, No-Code et vibe coding, avec une solide expérience WordPress.");
 m('meta[name="keywords"]','Sana Rachdi, développement web, Symfony 8, IA, Vibe Coding, No-Code, Bubble, Git, Docker, Figma, WordPress, Perpignan');
 m('meta[property="og:title"]','Sana Rachdi | Développement · IA · No-Code');
 m('meta[property="og:description"]','Je conçois des applications et outils digitaux en combinant développement, IA, No-Code et expérience utilisateur.');
 const nav=document.querySelector('.site-nav');if(nav&&!nav.querySelector('[href="#wordpress"]')){const a=document.createElement('a');a.href='#wordpress';a.textContent='WordPress';nav.insertBefore(a,nav.querySelector('[href="#process"]'))}
 const q=s=>document.querySelector(s);if(q('.hero-copy .eyebrow'))q('.hero-copy .eyebrow').textContent='Développement · IA · No-Code · Vibe Coding';
 if(q('.hero-copy h1'))q('.hero-copy h1').innerHTML='Je conçois des <em>applications utiles</em> avec le code, l’IA et le No-Code.';
 if(q('.hero-text'))q('.hero-text').textContent='Conceptrice d’applications en formation, je développe des solutions web en combinant Symfony, PHP, IA, No-Code, bases de données et UX/UI. J’utilise aussi le vibe coding et des workflows structurés avec Git, Docker et des prompts/agents en Markdown.';
 if(q('.profile-head p'))q('.profile-head p').textContent='Conceptrice d’applications · Dev & IA';
 if(q('.profile-stack'))q('.profile-stack').innerHTML='<span>Symfony 8</span><span>PHP</span><span>Git</span><span>Docker</span><span>Bubble</span><span>OpenAI</span>';
 if(q('.profile-value ul'))q('.profile-value ul').innerHTML='<li>Analyse des besoins et vision produit</li><li>Applications web et outils métiers</li><li>Développement assisté par IA / vibe coding</li><li>Automatisation et interfaces UX/UI</li>';
 const st=document.querySelectorAll('.stats article');if(st[1])st[1].innerHTML='<strong>8+</strong><span>projets et prototypes</span>';if(st[3])st[3].innerHTML='<strong>360°</strong><span>Produit, développement et IA</span>';
 if(q('.skills-grid'))q('.skills-grid').innerHTML='<article class="skill-card reveal"><span class="skill-icon">01</span><h3>Développement web</h3><div class="chips"><span>Symfony 8</span><span>PHP</span><span>HTML</span><span>CSS</span><span>JavaScript</span><span>Python</span><span>SQL</span></div></article><article class="skill-card reveal"><span class="skill-icon">02</span><h3>IA & Vibe Coding</h3><div class="chips"><span>ChatGPT</span><span>Codex</span><span>Agents IA</span><span>Prompt Engineering</span><span>Prompts .md</span><span>Orchestration d’agents</span></div></article><article class="skill-card reveal"><span class="skill-icon">03</span><h3>Environnements & workflow</h3><div class="chips"><span>Git</span><span>GitHub</span><span>Docker</span><span>Composer</span><span>CLI</span><span>Versioning</span></div></article><article class="skill-card reveal"><span class="skill-icon">04</span><h3>No-Code & Automatisation</h3><div class="chips"><span>Bubble</span><span>Make</span><span>n8n</span><span>Airtable</span><span>Notion</span></div></article><article class="skill-card reveal"><span class="skill-icon">05</span><h3>UX/UI & Conception</h3><div class="chips"><span>Figma</span><span>Wireframes</span><span>Auto Layout</span><span>Design System</span><span>UML</span><span>Merise</span></div></article><article class="skill-card reveal"><span class="skill-icon">06</span><h3>WordPress & Web</h3><div class="chips"><span>WordPress</span><span>Elementor</span><span>WooCommerce</span><span>SEO technique</span><span>GA4</span><span>Search Console</span></div></article>';
 const pg=q('.project-grid');if(pg&&!q('[data-project="symfony-todo"]'))pg.insertAdjacentHTML('afterbegin','<article class="project-card featured reveal" data-category="web ia"><div class="project-visual symfony"><span>Symfony 8 · ToDo</span></div><div class="project-content"><div class="chips"><span>Symfony 8</span><span>PHP</span><span>Doctrine</span><span>Git</span></div><h3>Application ToDo Symfony</h3><p>Application web avec authentification, inscription, gestion des utilisateurs et CRUD des tâches, développée dans une architecture Symfony structurée.</p><div class="project-result"><strong>Focus</strong><span>Backend Symfony, sécurité, entités Doctrine, Twig et workflow Git.</span></div><button class="project-more" data-project="symfony-todo" type="button">Voir le détail</button></div></article><article class="project-card reveal" data-category="ia web"><div class="project-visual recruit"><span>Recruit’IT Assistant</span></div><div class="project-content"><div class="chips"><span>IA</span><span>HTML/CSS/JS</span><span>Prompting</span></div><h3>Recruit’IT Assistant</h3><p>Prototype pédagogique d’aide à l’analyse de profils IT : l’IA structure les faits, les informations manquantes et les questions à poser sans prendre de décision.</p><button class="project-more" data-project="recruit-it" type="button">Voir le détail</button></div></article>');
 const process=q('#process');if(process&&!q('#wordpress'))process.insertAdjacentHTML('beforebegin',`<section class="section wordpress-section" id="wordpress"><div class="section-heading reveal"><p class="eyebrow">Expérience WordPress</p><h2>Une sélection de sites que j’ai réalisés et maintenus.</h2><p>Conception, intégration Elementor, responsive, maintenance, optimisation SEO et suivi technique selon les besoins de chaque projet.</p></div><div class="wordpress-grid">${[['RE','Immobilier','Real Estate Caretaking','https://realestatecaretaking.com'],['FC','Industrie · Multilingue','Ferlam Compensateurs','https://ferlam-compensateurs.com'],['AH','Santé','ALTRA Healthcare','https://altra-healthcare.com'],['CM','Centre médical','Centre Médical Belle Épine','https://centremedicalbelleepine.fr'],['CO','Santé','Centre Osny','https://centreosny.fr'],['LB','Esthétique médicale','Laser Beauté Médical','https://laser-beaute-medical.com'],['CG','Cabinet · Multilingue','Cabinet Gameiro','https://cabinetgameiro.fr'],['AP','Télécom','ALTRA Phone','https://altra-phone.com'],['CH','Relation client','C&H Relation Center','https://chrelationcenter.com'],['DF','Nutrition','Diet Fine','https://diet-fine.fr'],['CL','Clinique','Clinique Oseraie','https://cliniqueoseraie.fr'],['LV','Ophtalmologie','Laser Vision Belle Épine','https://laservisionbelle-epine.com']].map(x=>`<article class="wordpress-card reveal"><div class="site-monogram">${x[0]}</div><div><p class="site-type">${x[1]}</p><h3>${x[2]}</h3><p>Conception, intégration responsive, maintenance et optimisation du site selon les besoins du projet.</p><a href="${x[3]}" target="_blank" rel="noreferrer">Visiter le site ↗</a></div></article>`).join('')}</div></section>`);
 if(q('.timeline'))q('.timeline').innerHTML='<article class="timeline-item reveal"><div class="timeline-date">2026 — 2027</div><div><h3>Conceptrice d\'Applications No-Code</h3><p class="muted">L\'IDEM · Formation RNCP niveau 6</p><p>Symfony 8, développement web, Bubble, automatisation, IA, UX/UI, bases de données, UML/Merise, Git, Docker et vibe coding supervisé.</p></div></article><article class="timeline-item reveal"><div class="timeline-date">Depuis 2026</div><div><h3>Product Builder & Automatisation IA</h3><p class="muted">Projets personnels et freelance</p><p>Applications web, prototypes, workflows d’automatisation, agents IA et prompting structuré.</p></div></article><article class="timeline-item reveal"><div class="timeline-date">2022 — 2025</div><div><h3>Développeuse WordPress & Web</h3><p class="muted">Altra Systems</p><p>Conception, intégration et maintenance de sites WordPress, responsive, optimisation technique et SEO.</p></div></article><article class="timeline-item reveal"><div class="timeline-date">2020 — 2022</div><div><h3>Master 2 Informatique</h3><p class="muted">Informatique distribuée</p><p>Architecture logicielle, développement, données et systèmes distribués.</p></div></article>';
 const css=document.createElement('style');css.textContent='.project-visual.symfony{background:linear-gradient(135deg,#111827,#2a3348 55%,#6d5dfc)}.project-visual.recruit{background:linear-gradient(135deg,#10223f,#193f68 55%,#7758ff)}.wordpress-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:18px}.wordpress-card{display:flex;gap:18px;padding:24px;border:1px solid var(--line);background:rgba(255,255,255,.035);border-radius:22px;transition:.25s}.wordpress-card:hover{transform:translateY(-4px);border-color:rgba(124,92,255,.45)}.site-monogram{width:50px;height:50px;flex:0 0 50px;border-radius:15px;display:grid;place-items:center;font-weight:800;background:linear-gradient(135deg,rgba(124,92,255,.28),rgba(36,211,194,.18));border:1px solid rgba(255,255,255,.1)}.wordpress-card h3{margin:4px 0 9px;font-size:1.05rem}.wordpress-card p:not(.site-type){margin:0 0 14px;color:var(--muted);font-size:.92rem;line-height:1.6}.site-type{margin:0;color:#55d6be;font-size:.72rem;text-transform:uppercase;letter-spacing:.1em;font-weight:700}.wordpress-card a{font-size:.86rem;font-weight:700;text-decoration:none}@media(max-width:1000px){.wordpress-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:640px){.wordpress-grid{grid-template-columns:1fr}}';document.head.appendChild(css)
}
upgradePortfolio();
const navToggle=document.querySelector('.nav-toggle');const siteNav=document.querySelector('.site-nav');
navToggle?.addEventListener('click',()=>{const open=siteNav.classList.toggle('open');navToggle.setAttribute('aria-expanded',String(open))});
siteNav?.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{siteNav.classList.remove('open');navToggle?.setAttribute('aria-expanded','false')}));
document.querySelectorAll('.filter').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('.filter').forEach(b=>b.classList.remove('active'));button.classList.add('active');const selected=button.dataset.filter;document.querySelectorAll('.project-card').forEach(card=>card.classList.toggle('hidden',selected!=='all'&&!card.dataset.category.includes(selected)))}));
const projectDetails={
 'symfony-todo':{title:'Application ToDo Symfony 8',category:'Symfony 8 · PHP · Doctrine · Twig · Git',visual:'linear-gradient(135deg,#111827,#2a3348 55%,#6d5dfc)',description:'Application web de gestion de tâches développée avec Symfony 8.',problem:'Mettre en pratique une architecture backend structurée avec authentification et relations entre entités.',solution:'Entités User et Todo, authentification, inscription, sécurité, CRUD, Twig et workflow Git.',impact:'Une base applicative complète démontrant le cycle de développement Symfony.',tools:['Symfony 8','PHP','Doctrine','Twig','Git'],gallery:[]},
 'recruit-it':{title:'Recruit’IT Assistant',category:'IA · HTML/CSS/JS · Prompt Engineering',visual:'linear-gradient(135deg,#10223f,#193f68 55%,#7758ff)',description:'Prototype local d’assistance au recrutement IT sur données fictives.',problem:'Structurer l’analyse sans inventer d’informations ni automatiser la décision.',solution:'Interface locale et prompts séparant faits, informations manquantes et questions.',impact:'Usage responsable de l’IA centré sur l’assistance et la traçabilité.',tools:['HTML','CSS','JavaScript','IA','Prompt Engineering'],gallery:[]},
 capsa:{title:'CAPSA Paradise Land',category:'UX/UI · SEO · Menu digital · Automatisation',visual:'linear-gradient(135deg,#103b32,#176a50 55%,#d09b28)',description:"Conception de l'écosystème digital d'un parc de loisirs et espace événementiel à Gafsa.",problem:"L'offre du lieu était dispersée et manquait d'une présentation digitale claire.",solution:"Architecture, maquettes UI, menu digital, SEO local, contenus et automatisations.",impact:"Une expérience plus cohérente et une meilleure visibilité locale.",tools:['Figma','WordPress','SEO local','UX/UI','Make'],gallery:[]},
 'rx-contracts':{title:'RX Contracts',category:'Python · Django · Gestion documentaire',visual:'linear-gradient(135deg,#2367ff,#20c7d9)',description:'Plateforme interne de gestion des contrats, prestataires, sites, litiges, documents et échéances.',problem:'Les informations étaient dispersées et les échéances difficiles à suivre.',solution:'Tableau de bord centralisé avec rôles, recherche, alertes et documents.',impact:'Centralisation de l’information et réduction des oublis.',tools:['Python','Django','SQL','Alertes','Dashboard'],gallery:['images/rx-contracts-1.png','images/rx-contracts-2.png','images/rx-contracts-3.png']},
 'assistant-ia':{title:'Assistant IA de triage',category:'Make · OpenAI · Airtable',visual:'linear-gradient(135deg,#7c3aed,#db2777)',description:'Workflow IA pour analyser et structurer des demandes entrantes.',problem:'Le tri manuel demande du temps et crée des retards.',solution:'Un scénario Make qualifie la demande et prépare un brouillon avec validation humaine.',impact:'Traitement plus rapide et diminution des oublis.',tools:['Make','OpenAI','Airtable','Notion'],gallery:['images/assistant-ia-automation-1.png','images/assistant-ia-automation-2.png']},
 'agent-seo':{title:'Agent IA SEO WordPress',category:'IA · SEO · WordPress',visual:'linear-gradient(135deg,#111827,#334155)',description:'Prototype d’agent IA proposant des optimisations SEO actionnables.',problem:'Les audits manuels sont répétitifs.',solution:'Analyse titres, métadonnées, structure, contenu et maillage.',impact:'Audits plus rapides et recommandations standardisées.',tools:['WordPress','OpenAI','Make','SEO'],gallery:['images/agent-ia-seo.png']},
 'rib-generator':{title:'RIB Generator',category:'Python · Automatisation locale',visual:'linear-gradient(135deg,#059669,#14b8a6)',description:'Application desktop pour générer des fichiers comptables TXT conformes.',problem:'La saisie manuelle était lente et exposée aux erreurs.',solution:'Interface guidée, validations et génération automatique.',impact:'Gain de temps et meilleure fiabilité.',tools:['Python','CustomTkinter','TXT'],gallery:['images/rib-generator.png']},
 airbnb:{title:'Application de réservation No-Code',category:'Bubble · Figma · UML · Base de données',visual:'linear-gradient(135deg,#ff625f,#ff9b93)',description:'Projet de conception d’une application de réservation inspirée d’Airbnb.',problem:'Concevoir une application réaliste avec plusieurs profils.',solution:'Cas d’utilisation, modèle de données, parcours, maquettes et MVP Bubble.',impact:'Démarche produit complète, de l’analyse au prototype.',tools:['Bubble','Figma','UML','Merise'],gallery:[]}
};
const modal=document.querySelector('#project-modal');
function openModal(id){const p=projectDetails[id];if(!p||!modal)return;document.querySelector('#modal-title').textContent=p.title;document.querySelector('#modal-category').textContent=p.category;document.querySelector('#modal-description').textContent=p.description;document.querySelector('#modal-problem').textContent=p.problem;document.querySelector('#modal-solution').textContent=p.solution;document.querySelector('#modal-impact').textContent=p.impact;document.querySelector('#modal-visual').style.background=p.visual;document.querySelector('#modal-tools').innerHTML=p.tools.map(x=>`<span>${x}</span>`).join('');document.querySelector('#modal-gallery').innerHTML=p.gallery.map((src,i)=>`<figure class="modal-shot"><img src="${src}" alt="${p.title} - capture ${i+1}"><figcaption>${p.title} · capture ${i+1}</figcaption></figure>`).join('');modal.classList.add('open');modal.setAttribute('aria-hidden','false');document.body.classList.add('modal-lock')}
function closeModal(){modal?.classList.remove('open');modal?.setAttribute('aria-hidden','true');document.body.classList.remove('modal-lock')}
document.querySelectorAll('.project-more').forEach(b=>b.addEventListener('click',()=>openModal(b.dataset.project)));document.querySelectorAll('[data-close-modal]').forEach(x=>x.addEventListener('click',closeModal));document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()});
const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');observer.unobserve(entry.target)}}),{threshold:.12});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));document.querySelector('#year').textContent=new Date().getFullYear();
